### ISSUE TITLE
Scan card failed

### ISSUE THREAD

**Issue by sajjadjaved01** [faceterteam/PayCards_Android#23]
I am using Nokia 3, Oreo

2018-10-10 13:16:52.901 com.quellxcode.veasecustomer E/ScanCardActivity: Scan card failed
    java.lang.RuntimeException: onScanCardFinishedWithError()
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onScanCardFailed(ScanCardActivity.java:72)
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2844)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2969)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6733)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
     Caused by: cards.pay.paycardsrecognizer.sdk.camera.RecognitionUnavailableException: Unsupported architecture
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2844) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2969) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:206) 
        at android.app.ActivityThread.main(ActivityThread.java:6733) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

**Comment by willks** [comment]
I get exactly the same thing on Nokia 5, Oreo.

Looks like we're going to have to roll our own solution as all the card scanners out there are horribly broken or no longer supported.

Is this project still maintained?
