### ISSUE TITLE
nothing happen with android8

### ISSUE THREAD

**Issue by AymenSoft** [faceterteam/PayCards_Android#24]
i'm using paycards in my app, in android8 when click on button to start scan intent, nothing happen, can any one help

**Comment by daniil-pastuhov** [comment]
Logs:
```
2018-11-26 12:25:48.272 15547-15547/my.package E/ScanCardActivity: Scan card failed
    java.lang.RuntimeException: onScanCardFinishedWithError()
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onScanCardFailed(ScanCardActivity.java:72)
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: cards.pay.paycardsrecognizer.sdk.camera.RecognitionUnavailableException: Unsupported architecture
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by AymenSoft** [comment]
@daniil-pastuhov thank you for log, so is there any helpful solution for that

**Comment by daniil-pastuhov** [comment]
@AymenSoft 

I see also `E/Parcel: Class not found when unmarshalling: cards.pay.paycardsrecognizer.sdk.ui.ScanCardRequest`

But unfortunately don't see any solution now :(

**Comment by tommybuonomo** [comment]
By searching into the library, I found that the RecognitionCoreNdk couldn't be initialize with an error `Fatal Exception: java.lang.UnsatisfiedLinkError`.
Following [this article](https://medium.com/mobiwise-blog/unsatisfiedlinkerror-problem-on-some-android-devices-b77f2f83837d) I added this filters into the build.gradle:
```
defaultConfig {
    ...
    ndk {
        abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
    }
}
```

And it works

**Comment by OfsTr** [comment]
@tommybuonomo it's working, thank you for solution
