### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by hiteshsarsava** [faceterteam/PayCards_Android#33]
This library not supported to android x. How to convert support library to androidx. I have tried this library to convert in androidx. I am having following issue. Provided below stacktree for that:

```
2019-06-25 15:56:29.661 24894-24894/com.myapplication E/ScanCardActivity: Scan card failed
    java.lang.RuntimeException: onScanCardFinishedWithError()
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onScanCardFailed(ScanCardActivity.java:71)
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: cards.pay.paycardsrecognizer.sdk.camera.RecognitionUnavailableException: Unsupported architecture
        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:7032) 
        at android.app.Activity.performCreate(Activity.java:7023) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 

```

**Comment by richanshah** [comment]
Is there any way to not getting this issue ,I also have same issue like this

**Comment by MtsRovari** [comment]
Same issue..

**Comment by anthonycmain** [comment]
+1 this means its unusable going forwards until fixed

**Comment by benjabrons09** [comment]
+1 would be useful

**Comment by ThinkDigitalSoftware** [comment]
Converting it with Android Studio didn't work?

**Comment by richanshah** [comment]
nope it didn't allow to access some classes
