### ISSUE TITLE
RecognitionUnavailableException

### ISSUE THREAD

**Issue by phileo** [faceterteam/PayCards_Android#5]
The app in the play store works on the target device, but when I try to integrate into my project and run on same device, I get the following exception.  Any ideas or suggestions on how I can resolve this?

=======================================================
ScanCardActivity: Scan card failed
                                                                                    java.lang.RuntimeException: onScanCardFinishedWithError()
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onScanCardFailed(ScanCardActivity.java:72)
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36)
                                                                                        at android.app.Activity.performCreate(Activity.java:6975)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                     Caused by: cards.pay.paycardsrecognizer.sdk.camera.RecognitionUnavailableException: Unsupported architecture
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36) 
                                                                                        at android.app.Activity.performCreate(Activity.java:6975) 
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541)

**Comment by phileo** [comment]
The very first time I try to launch ScanCardActivity, i get this exception:

ScanCardActivity: Init library failed
                                                                                    java.lang.RuntimeException: onInitLibraryFailed()
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onInitLibraryFailed(ScanCardActivity.java:89)
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.InitLibraryFragment$DeployCoreTask.onPostExecute(InitLibraryFragment.java:193)
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.InitLibraryFragment$DeployCoreTask.onPostExecute(InitLibraryFragment.java:152)
                                                                                        at android.os.AsyncTask.finish(AsyncTask.java:695)
                                                                                        at android.os.AsyncTask.-wrap1(Unknown Source:0)
                                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                     Caused by: cards.pay.paycardsrecognizer.sdk.camera.RecognitionUnavailableException
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.InitLibraryFragment$DeployCoreTask.doInBackground(InitLibraryFragment.java:173)
                                                                                        at cards.pay.paycardsrecognizer.sdk.ui.InitLibraryFragment$DeployCoreTask.doInBackground(InitLibraryFragment.java:152)
                                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

**Comment by phileo** [comment]
gradle build system cannot find libopencv_jav3.so

I have included the PayCard sdk as a lib module with this path in my app module's build.gradle:
compile project(path: ':ParentLibFolder:scanPayCardSdk')

In the working demo project, the app module sets the scanPayCard sdk this way:
compile project(path: ":sdk")

How can I fix this?

================
```
zygote64: Got a deoptimization request on un-deoptimizable method java.io.FileDescriptor libcore.io.Linux.open(java.lang.String, int, int)
10-20 17:38:19.606 20654-20809/com.stonebridge.xumi.android.dev W/System.err: java.lang.UnsatisfiedLinkError: 

dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.stonebridge.xumi.android.dev-adRyAlQzuk8LRtYvrI21Cw==/base.apk"],nativeLibraryDirectories=[/data/app/com.stonebridge.xumi.android.dev-adRyAlQzuk8LRtYvrI21Cw==/lib/arm64, /data/app/com.stonebridge.xumi.android.dev-adRyAlQzuk8LRtYvrI21Cw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libopencv_java3.so"
10-20 17:38:19.607 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
10-20 17:38:19.608 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at java.lang.System.loadLibrary(System.java:1657)
10-20 17:38:19.608 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at cards.pay.paycardsrecognizer.sdk.ndk.RecognitionCoreNdk.<clinit>(RecognitionCoreNdk.java:36)
10-20 17:38:19.609 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at cards.pay.paycardsrecognizer.sdk.ndk.RecognitionCoreNdk.getInstance(RecognitionCoreNdk.java:31)
10-20 17:38:19.611 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at cards.pay.paycardsrecognizer.sdk.ndk.RecognitionCore.deploy(RecognitionCore.java:33)
10-20 17:38:19.611 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at cards.pay.paycardsrecognizer.sdk.camera.RecognitionCoreUtils.deployRecognitionCoreSync(RecognitionCoreUtils.java:32)
10-20 17:38:19.612 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at cards.pay.paycardsrecognizer.sdk.ui.InitLibraryFragment$DeployCoreTask.doInBackground(InitLibraryFragment.java:171)
10-20 17:38:19.613 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at cards.pay.paycardsrecognizer.sdk.ui.InitLibraryFragment$DeployCoreTask.doInBackground(InitLibraryFragment.java:152)
10-20 17:38:19.613 20654-20809/com.stonebridge.xumi.android.dev W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
```

**Comment by alexeymorozua** [comment]
I also have this problem

**Comment by gouthamiyyappan** [comment]
Unable to open camera to scan card.
Facing the same issue. Is this a bug in the library 
Anyone knows how to solve it?

Error Log:
ScanCardActivity: Scan card failed
  java.lang.RuntimeException: onScanCardFinishedWithError()  at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onScanCardFailed(ScanCardActivity.java:72)

Caused by: cards.pay.paycardsrecognizer.sdk.camera.RecognitionUnavailableException: Unsupported architecture
 at cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity.onCreate(ScanCardActivity.java:36)

**Comment by Michaos** [comment]
Same issue here, and by removing "compile 'me.dm7.barcodescanner:zbar:1.8.4'" from my app's build.gradle, the issue is gone.

**Comment by Gopinathsvlr** [comment]
Here is the fix by phileo. Download sdk from below one. 

https://github.com/phileo/PayCards_Android/tree/missing_abis

**Comment by pmbfish40** [comment]
Any news from this exception?
